# -----------------------------------------------------------------------------
# GENERAL
# -----------------------------------------------------------------------------

model = "gpt-5.2-codex"
review_model = "gpt-5.2-codex"
model_reasoning_effort = "high"
model_verbosity = "low"
model_reasoning_summary = "detailed"

# -----------------------------------------------------------------------------
# PERMISSIONS
# -----------------------------------------------------------------------------

approval_policy = "never"
sandbox_mode = "danger-full-access"

[sandbox_workspace_write]
exclude_slash_tmp = false
network_access = true

[shell_environment_policy]
# "all", "core", "none"
inherit = "core"

# -----------------------------------------------------------------------------
# FEATURES
# -----------------------------------------------------------------------------

[features]
apply_patch_freeform = true
collab = true # EXP
remote_compaction = true
shell_snapshot = true
skills = true
unified_exec = true

# steer = ENTER ; queue = TAB
steer = true

# disable builtin web search, use research skills
web_search_request = false

# -----------------------------------------------------------------------------
# MISC
# -----------------------------------------------------------------------------
[history]
persistence = "save-all"

[analytics]
enabled = false

[feedback]
enabled = false

[notice]
hide_rate_limit_model_nudge = true
