# -----------------------------------------------------------------------------
# GENERAL
# -----------------------------------------------------------------------------

model = "gpt-5.2-codex"
review_model = "gpt-5.2-codex"
model_reasoning_effort = "high"
model_verbosity = "low"
model_reasoning_summary = "detailed"

# -----------------------------------------------------------------------------
# PERMISSIONS
# -----------------------------------------------------------------------------

approval_policy = "never"
sandbox_mode = "danger-full-access"

[sandbox_workspace_write]
exclude_slash_tmp = false
network_access = true

[shell_environment_policy]
# "all", "core", "none"
inherit = "core"

# -----------------------------------------------------------------------------
# FEATURES
# -----------------------------------------------------------------------------

[features]
apply_patch_freeform = true
collab = false # EXP
remote_compaction = true
shell_snapshot = true
skills = true
steer = true # ENTER = SEND ; TAB = queue
tui2 = false # EXP
unified_exec = true
web_search_request = true

# -----------------------------------------------------------------------------
# MCP
# -----------------------------------------------------------------------------

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

# -----------------------------------------------------------------------------
# MISC
# -----------------------------------------------------------------------------
[history]
persistence = "save-all"

[analytics]
enabled = false

[feedback]
enabled = false

[notice]
hide_rate_limit_model_nudge = true
