# -----------------------------------------------------------------------------
# GENERAL
# -----------------------------------------------------------------------------

model = "gpt-5.2-codex"
model_reasoning_effort = "high"
tool_output_token_limit = 25000
model_auto_compact_token_limit = 233000

# -----------------------------------------------------------------------------
# PERMISSIONS
# -----------------------------------------------------------------------------

approval_policy = "never"
sandbox_mode = "danger-full-access"

[sandbox_workspace_write]
exclude_slash_tmp = false
network_access = true

[shell_environment_policy]
# "all", "core", "none"
inherit = "core"

# -----------------------------------------------------------------------------
# FEATURES
# -----------------------------------------------------------------------------

[features]
apply_patch_freeform = true
collab = true # EXP
ghost_commit = false
remote_compaction = true
shell_snapshot = true
skills = true
steer = true # ENTER = SEND ; TAB = queue
unified_exec = true
web_search_request = true

# -----------------------------------------------------------------------------
# MCP
# -----------------------------------------------------------------------------

[mcp_servers.deepwiki]
url = "https://mcp.deepwiki.com/mcp"

# -----------------------------------------------------------------------------
# PROVIDERS
# -----------------------------------------------------------------------------

[model_providers.zai]
name = "z.ai - GLM"
base_url = "https://api.z.ai/api/coding/paas/v4"
env_key = "ZAI_API_KEY"
wire_api = "responses"

# -----------------------------------------------------------------------------
# MODELS
# -----------------------------------------------------------------------------

[profiles.glm_4_7]
model = "glm-4.7"
model_provider = "zai"

# -----------------------------------------------------------------------------
# MISC
# -----------------------------------------------------------------------------

[notice]
hide_rate_limit_model_nudge = true
